library(Biobase)
library(GEOquery)
geoq=getGEO("GSE9514")
names(geoq)
geoq[1]
class(geoq)
e=geoq[[1]]
e
exprs(geoq[[1]])[1:3,1:3]
exprs(e)[1:3,1:3]
dim(exprs(e))
dim(pData(e))
names(pData(e))
pData(e)$characteristics_ch1
fData(e)[1:3,1:3]
dim(fData(e))
names(fData(e))
head(fData(e)[17])
head(fData(e)$"Gene Symbol")
head(rownames(e))
experimentData(e)
annotation(e)
l
source("https://bioconductor.org/biocLite.R")
biocLite("parathyroidSE")
ibrary(parathyroidSE)
data("parathyroidGenesSE")
se=parathyroidGenesSE
se
browseVignettes("parathyroidSE")
assay(se)[1:3,1:3]
dim(assay(se))
colData(se)[1:3,1:6]
colData(se)$treatment
rowData(Se)[1]
rowRanges(se)[1]
version
biocVersion()
class(rowRanges(se))
length(rowRanges(se))
head(rownames(se))
exptData(se)$MIAME
library(devtools)
install_github("genomicsclass/GSE5859Subset")
library(GSE5859Subset)
data(GSE5859Subset)
dim(geneExpression)
library(GSE5859Subset)

data(GSE5859Subset)
data(package="GSE5859Subset")
head(geneExpression)
head(sampleInfo)
sampleInfo
head(geneAnnotation)
class(geneExpression)
class(sampleInfo)
class(geneAnnotation)
identical(colnames(geneExpression),sampleInfo$filename)
identical(rownames(geneExpression),geneAnnotation$PROBEID)
library(Biobase)
rownames(sampleInfo)=sampleInfo$filename
head(sampleInfo)
rownames(geneAnnotation)=geneAnnotation$PROBEID
head(geneAnnotation)
eset=ExpressionSet(assayData=geneExpression,phenoData = AnnotatedDataFrame(sampleInfo),featureData = AnnotatedDataFrame(geneAnnotation))
eset
library(Homo.sapiens)
genes=genes(Homo.sapiens)
head(genes)
seqinfo(genes)
seqnames(genes)
table(seqnames(genes)[1:24])
seqnames(genes)[1:10]
?CHR
seqlevels(genes)
library(hgfocus.db)
library(BiocInstaller)
biocLite("hgfocus.db")
n
??GSE5859Subset
map=select(hgfocus.db,keys = featureNames(eset),columns = "ENTREZID",keytype = "PROBEID")
head(map)
head(genes)
head(metadata(genes))
metadata(genes)
colnames(genes)
metadata(genes)$GENEID
mcols(genes)
head(map)
index1=match(featureNames(eset),map[,1])
head(index1)
index2=match(map[index1,2],as.character(mcols(genes)$GENEID))
head(index2)
head(genes)
index3=which(!is.na(index2))
index2=index2[index3]
head(index2)
genes=genes[index2,]
neweset=eset[index3,]
se=SummarizedExperiment(assays = exprs(neweset),rowRanges=genes,colData=DataFrame(pData(neweset)))
  
neweset
head(genes)               
?SummarizedExperiment
?metadata
se$group
colnames(se)
colData(se)
